// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEMpbAgB5Ly3DZV9wGW0RYoIgO5J6N-xU',
    appId: '1:971449413886:web:905921f29bcb2fd51ab5af',
    messagingSenderId: '971449413886',
    projectId: 'kidtang-97499',
    authDomain: 'kidtang-97499.firebaseapp.com',
    storageBucket: 'kidtang-97499.firebasestorage.app',
    measurementId: 'G-1SR9G7H0VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXo9Ar3Iiz7KxGDtmCB7gmqY65pwd4U4',
    appId: '1:971449413886:android:c43b880df4459bbb1ab5af',
    messagingSenderId: '971449413886',
    projectId: 'kidtang-97499',
    storageBucket: 'kidtang-97499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00MYK5o7wKiRPDLOeYhN3E3Z5bupL-h0',
    appId: '1:971449413886:ios:3bc31c2fc8b9e60e1ab5af',
    messagingSenderId: '971449413886',
    projectId: 'kidtang-97499',
    storageBucket: 'kidtang-97499.firebasestorage.app',
    iosBundleId: 'com.kidtang.kidtangFlutter',
  );
}
